### ISSUE TITLE
Not working on Steam Edition + Download Link for Game is down

### ISSUE THREAD

**Issue by Mirco1502** [dong-nguyen-hd/Sun-Collector#1]
Hello there,

I tried this with the Steam Version and it's not working for me sadly.

Can you maybe add more instructions how to use it? Does the file need to be in the game directory? Do you need to rename it?

Also the Downloadlink for the Game + Mod is down

Thanks for your work, i would love to get this to run!

Greetings

**Comment by dong-nguyen-hd** [comment]
It currently does not support the Steam version. I have updated the download link

**Comment by Mirco1502** [comment]
Thank you very much!
